import { MigrationInterface, QueryRunner } from "typeorm";

export class MyMigration1707403658290 implements MigrationInterface {
    name = 'MyMigration1707403658290'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_314680784cc4ba14bf392fbb873"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_cc28874faae9823b38853f20823"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_ee32567be3d2ffe62b4f000fee6"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_f2eb144e4caa370c885ae2464aa"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP CONSTRAINT "FK_829fabbd5394610739e5bb6746f"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP CONSTRAINT "FK_24ad14188b37dcd8686bf0d3862"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP CONSTRAINT "FK_6a11bf180a267179e3feed77073"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP CONSTRAINT "FK_26d6ce48d2b0dd8353a4df44ca7"`);
        await queryRunner.query(`ALTER TABLE "following" DROP CONSTRAINT "FK_3222246b2ad81e4873958f7aaff"`);
        await queryRunner.query(`ALTER TABLE "following" DROP CONSTRAINT "FK_e2ea36410efcf585a78eb658786"`);
        await queryRunner.query(`ALTER TABLE "following" DROP CONSTRAINT "FK_b8d802a9eaa03196014572c0bc9"`);
        await queryRunner.query(`ALTER TABLE "following" DROP CONSTRAINT "FK_acd053771e38901530f489a9813"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "userIdId"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "threadIdId"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "userIdId"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "threadIdId"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "followingIdId"`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "followerIdId"`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "thread_id" integer`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "thread_id" integer`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "following" ADD "following_id" integer`);
        await queryRunner.query(`ALTER TABLE "following" ADD "follower_id" integer`);
        await queryRunner.query(`ALTER TABLE "following" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "following" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "threads" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "threads" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "threads" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "threads" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "following" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "following" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_3f519ed95f775c781a254089171" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_dfee0c14f2a697eeb0b0bfc50cc" FOREIGN KEY ("thread_id") REFERENCES "threads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_46bbc2d9f821f709d3c0edad996" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_6488e67d2031d1f13b4e2936eeb" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "replies" ADD CONSTRAINT "FK_c961efa3687d100ed22cd409534" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "replies" ADD CONSTRAINT "FK_1af58ca9000874da2171004d164" FOREIGN KEY ("thread_id") REFERENCES "threads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "replies" ADD CONSTRAINT "FK_b3b23940f28ee0f35e33d7ee975" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "replies" ADD CONSTRAINT "FK_cbe71f1fd023ef4a303fffef478" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "following" ADD CONSTRAINT "FK_45428a713ee7d51def21b67ff20" FOREIGN KEY ("following_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "following" ADD CONSTRAINT "FK_59f580ba79fe33c121f8c3cc095" FOREIGN KEY ("follower_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "following" ADD CONSTRAINT "FK_c77397d3c3b96c577b14c01d108" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "following" ADD CONSTRAINT "FK_96c282df3b5b7b1247dc1a66d7f" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "following" DROP CONSTRAINT "FK_96c282df3b5b7b1247dc1a66d7f"`);
        await queryRunner.query(`ALTER TABLE "following" DROP CONSTRAINT "FK_c77397d3c3b96c577b14c01d108"`);
        await queryRunner.query(`ALTER TABLE "following" DROP CONSTRAINT "FK_59f580ba79fe33c121f8c3cc095"`);
        await queryRunner.query(`ALTER TABLE "following" DROP CONSTRAINT "FK_45428a713ee7d51def21b67ff20"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP CONSTRAINT "FK_cbe71f1fd023ef4a303fffef478"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP CONSTRAINT "FK_b3b23940f28ee0f35e33d7ee975"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP CONSTRAINT "FK_1af58ca9000874da2171004d164"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP CONSTRAINT "FK_c961efa3687d100ed22cd409534"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_6488e67d2031d1f13b4e2936eeb"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_46bbc2d9f821f709d3c0edad996"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_dfee0c14f2a697eeb0b0bfc50cc"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_3f519ed95f775c781a254089171"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "following" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "following" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "threads" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "threads" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "threads" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "threads" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "follower_id"`);
        await queryRunner.query(`ALTER TABLE "following" DROP COLUMN "following_id"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "thread_id"`);
        await queryRunner.query(`ALTER TABLE "replies" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "thread_id"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "following" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "following" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "following" ADD "followerIdId" integer`);
        await queryRunner.query(`ALTER TABLE "following" ADD "followingIdId" integer`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "threadIdId" integer`);
        await queryRunner.query(`ALTER TABLE "replies" ADD "userIdId" integer`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "threadIdId" integer`);
        await queryRunner.query(`ALTER TABLE "likes" ADD "userIdId" integer`);
        await queryRunner.query(`ALTER TABLE "following" ADD CONSTRAINT "FK_acd053771e38901530f489a9813" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "following" ADD CONSTRAINT "FK_b8d802a9eaa03196014572c0bc9" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "following" ADD CONSTRAINT "FK_e2ea36410efcf585a78eb658786" FOREIGN KEY ("followerIdId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "following" ADD CONSTRAINT "FK_3222246b2ad81e4873958f7aaff" FOREIGN KEY ("followingIdId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "replies" ADD CONSTRAINT "FK_26d6ce48d2b0dd8353a4df44ca7" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "replies" ADD CONSTRAINT "FK_6a11bf180a267179e3feed77073" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "replies" ADD CONSTRAINT "FK_24ad14188b37dcd8686bf0d3862" FOREIGN KEY ("threadIdId") REFERENCES "threads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "replies" ADD CONSTRAINT "FK_829fabbd5394610739e5bb6746f" FOREIGN KEY ("userIdId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_f2eb144e4caa370c885ae2464aa" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_ee32567be3d2ffe62b4f000fee6" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_cc28874faae9823b38853f20823" FOREIGN KEY ("threadIdId") REFERENCES "threads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_314680784cc4ba14bf392fbb873" FOREIGN KEY ("userIdId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
